Create assets on release
primesearch/mfakto pull request #12
Opened 2024-11-29 19:28 UTC by henning-gerhardt

On creating tags for releases this change will introduce an automatic build on Linux, Windows and MacOS to build the needed release assets to use mfakto on this operating systems.

Some information:
- I used the v0.16-beta2 Windows build as a base for building the assets
- Creating the Windows version with VS is failing with an error message which I don't know to solve as I has no access to a Windows system. If I get the way how to build them I can include the solution in this pull request or it must be later adjusted.

2024-11-30 09:53 UTC, henning-gerhardt commented
Maybe super seeded by #13.

2025-01-05 07:51 UTC, proski requested changes
Please see my comments for #13, they apply here as well.

2025-01-05 07:51 UTC, proski commented on .github/workflows/buildrelease.yml
> +        brew install pocl
pocl should not be needed to build mfakto on MacOS.

2025-01-05 08:02 UTC, henning-gerhardt commented
> Please see my comments for #13, they apply here as well.

If #13 got merged this pull request is not needed anymore.

2025-01-05 08:03 UTC, henning-gerhardt commented on .github/workflows/buildrelease.yml
> +        brew install pocl
This was my first attempt to build release builds by duplicating the build process from the CI run. So this should be changed in the CI too. But I'm not familiar with MacOS and what there is needed.

2025-02-05 06:44 UTC, henning-gerhardt commented
Closing in favor of #13.

2025-02-05 06:44 UTC, closed without merging