Build artifact and release assets
primesearch/mfakto pull request #13
Opened 2024-11-30 09:53 UTC by henning-gerhardt

This pull request may superseed #12.

Instead of running two workflows and two possible different builds the created files from the CI workflow are used to create even the release builds assets. Benefit is that every build now create all artifacts assets for every operation system so even without a release every one on every supported operation system can try the most recent version out without the need to build mfakto itself.

I discovered too how to build the artifact and release assert on windows-msvc. This can even be pack ported to #12 if two independent build workflows should be used.

I could only test the created Linux based assets in a successful way, so Windows and MacOS should be tested who can access them.

2024-11-30 10:17 UTC, henning-gerhardt commented
With the latest change I created a new test tag https://github.com/henning-gerhardt/mfakto/releases/tag/v0.0.3. 

The build artifacts are available under https://github.com/primesearch/mfakto/actions/runs/12095551380 for the latest changes of this pull request. After this change is merged they are available under https://github.com/primesearch/mfakto/actions -> Commit name -> Artifacts

2024-12-07 16:07 UTC, jcoxdco commented
I pulled down mfakto-v0.0.2-windows-msvc. Self tests passed. Windows 11, RDNA3 7700 XT.
I didn't finish the TF of that exponent. I can if you think it is needed.

![image](https://github.com/user-attachments/assets/864bfd3f-f9b8-49d1-9410-082b248d043d)

2024-12-07 16:12 UTC, henning-gerhardt commented
Thank you for testing this build, jcoxdco. I'm hoping that the builds are helping everyone who want to use mfakto.

2025-01-05 07:38 UTC, proski requested changes

2025-01-05 07:38 UTC, proski commented on .github/workflows/ci.yml
> +        path: x64/Debug/
Does this package the debug build? I believe the release build would a better choice, especially for the users who download the binary without the sources.

2025-01-05 07:38 UTC, proski commented on .github/workflows/ci.yml
>          make -C src -O -j $env:NUMBER_OF_PROCESSORS CC=$env:CC CPP=$env:CPP AMD_APP_INCLUDE="-IC:\msys64\mingw64\include" AMD_APP_LIB="-LC:\msys64\mingw64\lib"
Maybe the binary release should use better optimization settings like `-O3`?

2025-01-05 07:38 UTC, proski commented on .github/workflows/ci.yml
> +           mfakto-windows-msys2.zip
What's the rationale for making two different builds for Windows available for download? The CI script checks two documented ways to build mfakto for Windows. Developers would care, as they use one or another. But why should the end users care?

2025-01-05 07:38 UTC, proski commented on .github/workflows/ci.yml
> +        name: mfakto-${{ matrix.os }}
I downloaded mfakto-macos-13.zip and tried running it on a Mac. I got 
```
Select device - Error: No platform found
ERROR: init_CL(3, 0) failed
```
That can be expected, as the binary is linked against pocl rather than against the MacOS OpenCL library. I believe separate builds would be needed to test mfakto with pocl and to distribute mfakto that uses the actual OpenCL.

Also, the binary names are misleading. The main difference between macos-13 and macos-14 on GitHub is that macos-13 is x86_64 and macos-14 is aarch64. It might be possible to make a fat binary to support both architectures.

2025-01-05 07:40 UTC, henning-gerhardt commented on .github/workflows/ci.yml
> +        path: x64/Debug/
Currently the debug build was in place which I used. A release build should be possible too. I must try it how to do this as I have only GitHub to build the Windows build.

2025-01-05 07:43 UTC, henning-gerhardt commented on .github/workflows/ci.yml
> +           mfakto-windows-msys2.zip
I don't know. I did only extending the existing builds. Which version is the better one on Windows?

2025-01-05 07:45 UTC, henning-gerhardt commented on .github/workflows/ci.yml
> +        name: mfakto-${{ matrix.os }}
You error message is good to know. How did the previous executed test success on GitHub but not on your system? I'm familiar only with Linux and do only guessing how it could work on Windows and MacOS.

2025-01-05 07:58 UTC, henning-gerhardt commented on .github/workflows/ci.yml
> +        path: x64/Debug/
I adjusted the build process to use a release build. I'm hoping this is working. Can someone please test it? Build should be available in a few minutes.

2025-01-08 08:25 UTC, proski commented on .github/workflows/ci.yml
> +           mfakto-windows-msys2.zip
It should be tested. Generally, the faster version should be used. If there is no significant difference in speed, I would go with MSYS2 because it's open source and because it shares the build system with Linux (the same compiler, the same compiler flags).

2025-01-08 16:35 UTC, henning-gerhardt commented on .github/workflows/ci.yml
> +        name: mfakto-${{ matrix.os }}
I removed the `pocl`  dependency from MacOS build but without this dependency the executed tests on MacOS on GitHub did not work anymore. For Windows builds there are no tests executed too so it should be okay for now.

2025-01-09 00:26 UTC, proski commented on .github/workflows/ci.yml
> +        name: mfakto-${{ matrix.os }}
We'll need two different builds, one for testing and another for distribution. We can only avoid it if it's possible to use the OpenCL linked binaries to use pocl at the runtime, but I read somewhere that it's impossible on MacOS, so I didn't try.

2025-01-09 16:44 UTC, henning-gerhardt commented on .github/workflows/ci.yml
> +        name: mfakto-${{ matrix.os }}
I see 3 possible options:
1. use the current version as is without test execution on the MacOS builds
2. use different builds for CI and making the builds file available. But this has 2 disadvantages: more files to maintain and if the CI build is failing then the other build will be continue
3. extend the current CI build for MacOS: Build with the `pocl` dependency and execute the tests. Then additional  `make clean` run and a normal `make` run without the `pocl` dependency and use this build for the downloadable files.

2025-01-10 23:57 UTC, proski commented on .github/workflows/ci.yml
> +        name: mfakto-${{ matrix.os }}
The number 3 would be the best.

2025-01-11 07:26 UTC, henning-gerhardt commented on .github/workflows/ci.yml
> +        name: mfakto-${{ matrix.os }}
I will try option 3 but this must wait a few days as I'm now on vacation.

2025-01-21 18:19 UTC, henning-gerhardt commented on .github/workflows/ci.yml
> +        name: mfakto-${{ matrix.os }}
Back from vacation and I adjusted the MacOS build with option 3: additional `make clean`  run and a `make` run without the pocl dependency in use.

@proski can you verify that both MacOS executables are now correct build? They are available at https://github.com/henning-gerhardt/mfakto/actions/runs/12893233610#artifacts

2025-01-22 08:20 UTC, proski commented on .github/workflows/ci.yml
> +        name: mfakto-${{ matrix.os }}
Yes, I can confirm that the macos-13 build is working on an Intel iMac with a Radeon.

2025-02-05 07:04 UTC, henning-gerhardt commented
I rebased this pull request to include the latest changes regarding the Makefile changes and smashed all MacOS related commits into one commit.

2025-02-05 08:26 UTC, proski commented on .github/workflows/ci.yml
> +           mfakto-windows-msys2.zip
I guess we can generate both MSVC and MSYS2 builds for PRs to make it easier to download and test both of them. It's up to the maintainer which build should be published as "the official Windows build" for releases.

2025-02-05 08:29 UTC, proski commented on .github/workflows/ci.yml
> +    - name: Build GitHub development version
This is misleading. There is nothing in this build that makes it the "GitHub development version". This could be "Build with pocl".

2025-02-05 08:31 UTC, proski commented on .github/workflows/ci.yml
> +    - name: Build user artifact without pocl dependency
This could be simply "Build" or "Build for native OpenCL". It's better to describe things but what they are than by what they are not :)

2025-02-05 10:28 UTC, henning-gerhardt commented on .github/workflows/ci.yml
> +    - name: Build GitHub development version
Changed.

2025-02-05 10:28 UTC, henning-gerhardt commented on .github/workflows/ci.yml
> +    - name: Build user artifact without pocl dependency
Changed.

2025-02-05 17:43 UTC, proski commented on .github/workflows/ci.yml
> +        path: x64/Debug/
I tested the build on Windows, it's working. The logs show it's a release build, the compiler flags show optimization. So it's a good build.
The MSYS2 build is not working for me, but that's a separate topic. It's good to have an option to download build artifacts and test them.

2025-02-05 17:43 UTC, proski approved these changes

2025-02-05 17:44 UTC, merged